AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Infraestructura mínima en AWS para Andres. Incluye EC2, IAM Role y buenas prácticas.

# -------------------
# Parámetros y Mappings
# -------------------
Parameters:
  DefaultVpcId:
    Type: String
    Default: vpc-086fe118b4ed5c6e4
    Description: VPC por defecto para todos los recursos

  # Se puede parametrizar la IP permitida si se requiere acceso restringido
  AllowedSSHLocation:
    Type: String
    Default: 0.0.0.0/0
    Description: Rango de IPs permitidas para acceso (ajustar según necesidad)

Mappings:
  RegionMap:
    # Amazon Linux 2023 AMI IDs por región (ejemplo, actualizar según región real)
    us-east-1:
      AMI: ami-0c101f26f147fa7fd
    us-west-2:
      AMI: ami-0e472ba40eb589f49
    eu-west-1:
      AMI: ami-0aef57767f5404a3c

# -------------------
# Recursos
# -------------------
Resources:
  # Instancia EC2 en subred pública de la VPC por defecto
  AndresEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId:
        Fn::FindInMap:
          - RegionMap
          - Ref: AWS::Region
          - AMI
      SubnetId:
        Fn::Select:
          - 0
          - Fn::GetAZs: ''
      # Se asume que la primera subred pública está en la lista de subredes de la VPC por defecto
      SecurityGroupIds:
        - Ref: DefaultSecurityGroup
      IamInstanceProfile: !Ref EC2InstanceProfile
      Tags:
        - Key: Name
          Value: andres-rodriguez-654654327431
    # Comentario: Instancia EC2 sin par de llaves SSH

  # Grupo de seguridad por defecto de la VPC
  DefaultSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Acceso mínimo para EC2 Andres
      VpcId: !Ref DefaultVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AllowedSSHLocation
      # Limitar puertos según necesidad
    # Comentario: Grupo de seguridad por defecto, solo permite SSH desde IPs permitidas

  # Rol IAM mínimo para EC2
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: EC2MinimalPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:Describe*
                Resource: '*'
    # Comentario: Rol IAM con privilegios mínimos para EC2

  # Instance Profile para asociar el rol a la instancia
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - Ref: EC2InstanceRole
    # Comentario: Instance Profile para EC2

# -------------------
# Salidas
# -------------------
Outputs:
  InstanceId:
    Description: ID de la instancia EC2 creada
    Value: !Ref AndresEC2Instance
  InstancePublicIp:
    Description: IP pública de la instancia EC2
    Value: !GetAtt AndresEC2Instance.PublicIp
  InstanceRole:
    Description: Nombre del rol IAM asociado a la instancia
    Value: !Ref EC2InstanceRole 